version: '3.8'

services:
  app:
    build:
      dockerfile: conf/docker/prod/Dockerfile
    environment:
      - DB_CONFIG=$DB_CONFIG
      - DBMATE_MIGRATIONS_DIR=$DBMATE_MIGRATIONS_DIR
      - PRODUCTION=$PRODUCTION
    volumes:
      - ./data/app_files:/bin/data/app_files
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    extends:
      file: conf/docker/docker-compose-base.yml
      service: db
    volumes:
      - ./data/pgdata:$PGDATA

  redis:
    extends:
      file: conf/docker/docker-compose-base.yml
      service: redis
    volumes:
      - ./data/redisdata:/data

networks:
  default:
    name: metroid_bookmarks_prod