version: '3.8'

services:
  app:
    build:
      dockerfile: conf/docker/prod/Dockerfile
    environment:
      - APP_CONFIG_PATH=$APP_CONFIG_PATH
      - PRODUCTION=$PRODUCTION
      - LOG_LEVEL=$LOG_LEVEL
      - MIN_CONNS=$MIN_CONNS
      - MAX_CONNS=$MAX_CONNS
      - MAX_CONN_LIFE_TIME=$MAX_CONN_LIFE_TIME
      - MAX_CONNIDLE_TIME=$MAX_CONNIDLE_TIME
      - HEALTH_CHECK_PERIOD=$HEALTH_CHECK_PERIOD
    volumes:
      - ./data/app_files:/bin/data/app_files
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    extends:
      file: conf/docker/docker-compose-base.yml
      service: db
    volumes:
      - ./data/pgdata:$PGDATA

  redis:
    extends:
      file: conf/docker/docker-compose-base.yml
      service: redis
    volumes:
      - ./data/redisdata:/data

networks:
  default:
    name: metroid_bookmarks_prod